name: Direct Sync to Docs
on:
  push:
    branches: [main]
    paths: ['api/openapi.yaml']
  workflow_dispatch:
    inputs:
      reason:
        description: "Why are you running this sync manually?"
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout Service Repo
        uses: actions/checkout@v4

      - name: Create Sync Config
        run: |
          mkdir -p .github
          cat <<EOF > .github/sync.yml
          abcdeafasdfasdf/doc:
            - source: api/openapi.yaml
              dest: api-reference/account/travellers/spec.yaml
          EOF

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.generate_token.outputs.token }}
          SKIP_PR: true
          COMMIT_PREFIX: "Sync: ${{ github.event.repository.name }} 🔄 "
