name: Direct Sync to Docs
on:
  push:
    branches: [main]
    paths: ["api/openapi.yaml"]
  workflow_dispatch:
    inputs:
      reason:
        description: "Why are you running this sync manually?"
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Push to Redocly
        run: |
          REDOCLY_AUTHORIZATION=sk_FTv600srVU_3Rj2AupCIXEs7oOveCHtizBBSx9Qf-_kMXe7VhQS8mfnWSC6lz7OBP5o \
          npx @redocly/cli push api/openapi.yaml \
            --organization "bnima" \
            --project "bnima" \
            --mount-path "/api-reference/remotes/cicd" \
            --branch "doc/main" \
            --author "API Sync Bot <bot@docs.com>" \
            --message "Hey" \
            --wait-for-deployment \
            --verbose
